version: "3.8"

services:
  itflow:
    build: .
    container_name: itflow
    ports:
      - "8080:80"
    environment:
      ITFLOW_NAME: "Imperium ITFlow"
      ITFLOW_URL: "http://localhost:8080"
      ITFLOW_PORT: 80
      ITFLOW_REPO: "github.com/itflow-org/itflow"
      ITFLOW_REPO_BRANCH: "master"
      ITFLOW_LOG_LEVEL: info
      ITFLOW_DB_HOST: itflow-db
      ITFLOW_DB_PASS: supersecretpassword
    depends_on:
      - itflow-db
    networks:
      - itflow-net
    volumes:
      - ./itflow:/var/www/html

  itflow-db:
    image: mariadb:10.6
    container_name: itflow-db
    restart: always
    environment:
      MARIADB_DATABASE: itflow
      MARIADB_USER: itflow
      MARIADB_PASSWORD: supersecretpassword
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - itflow-db-data:/var/lib/mysql
    networks:
      - itflow-net

volumes:
  itflow-db-data:

networks:
  itflow-net:
